### ISSUE TITLE
Target node v4 and ES6

### ISSUE THREAD

**Issue by oeuillot** [oeuillot/upnpserver#41]
I propose to target NodeJs 4 and ES6  (and discontinue NodeJS v2.x)

An opinion ?

**Comment by s-leger** [comment]
Why not, should not break anything.

**Comment by oeuillot** [comment]
I think so ;-)

And v4 improves performance and memory leaks of Buffer class too !


2015-09-10 10:42 GMT+02:00 s-leger <notifications@github.com>:

**Comment by oeuillot** [comment]
I have tested v4, and I fixed a little problem ... It seems working !

**Comment by s-leger** [comment]
Still have to update my node for mac.
Pretty cool as should be io.js branch, worried a bit about modules compatibility.

**Comment by oeuillot** [comment]
I have lot of problems, there are several internal asserts which throws Error occasionally !
A nightmare :

````
assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at ServerResponse.resOnFinish (_http_server.js:473:7)
    at emitNone (events.js:72:20)
    at ServerResponse.emit (events.js:166:7)
    at finish (_http_outgoing.js:526:10)
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)`

````

**Comment by s-leger** [comment]
Sniff
Io.js merge is a big step forward, and errors are parts of this game.
We have to wait a bit until they address such basic issues. 
Http server is overused module and many other users are impacted by this. 
So hope they fix this soon. Wait and see.
