### ISSUE TITLE
es6?

### ISSUE THREAD

**Issue by smolleyes** [oeuillot/upnpserver#51]
hello olivier

trying the new es6 branch

downloaded the zip and running npm install i have kerberos building fail...

```
> kerberos@0.0.18 install /home/sylvain/Documents/projets/git/StreamStudio/node_modules/upnpserver/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/home/sylvain/Documents/projets/git/StreamStudio/node_modules/upnpserver/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:36:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:37:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function ‘authenticate_gss_client_wrap’:
../lib/kerberosgss.c:362:19: warning: variable ‘server_conf_flags’ set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:930:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory '/home/sylvain/Documents/projets/git/StreamStudio/node_modules/upnpserver/node_modules/mongodb/node_modules/kerberos/build'
npm ERR! Linux 4.4.0-040400rc7-generic
npm ERR! argv "/home/sylvain/.nvm/versions/node/v4.2.4/bin/node" "/home/sylvain/.nvm/versions/node/v4.2.4/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package exif@0.5.1 does not satisfy its siblings' peerDependencies requirements!
```

i try to install exif

```
npm install exif
npm WARN package.json upnpserver@3.0.0 license should be a valid SPDX license expression
npm ERR! Linux 4.4.0-040400rc7-generic
npm ERR! argv "/home/sylvain/.nvm/versions/node/v4.2.4/bin/node" "/home/sylvain/.nvm/versions/node/v4.2.4/bin/npm" "install" "exif"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package exif@0.5.1 does not satisfy its siblings' peerDependencies requirements!

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sylvain/Documents/projets/git/StreamStudio/node_modules/upnpserver/npm-debug.log
```

?

**Comment by oeuillot** [comment]
Hello smolley,

Yes, I known all of these problems,

But each time, it is a dependency problem !
- Kerberos is used by mongodb  (and I can't change it)
- for node-exif, it seems that peerDependencies is not a solution for an
optional dependency. (I don't understand  exactly how it works !!!) [and I
am the new maintainer of node-exif]

I am working on "live" filesystem changes detection, add 1fichier and
googleDrive support,  and mysql storage.
I must modify IceCastRepository to use the last API.
I have done:
- nedb and mongodb storage support   (the ID of each resource doesn't
change at each startup anymore)
- videoRepositiory

Best,

Olivier

2016-01-27 9:35 GMT+01:00 smolleyes <notifications@github.com>:

**Comment by smolleyes** [comment]
yup i look at the files

so i have to found the missing dep ?

**Comment by smolleyes** [comment]
strange

replaces "latest" by ^0.5.1 for the exif dep in package.json and no more errors ....

**Comment by oeuillot** [comment]
Good news, I do it immediately :-p

2016-01-27 10:01 GMT+01:00 smolleyes <notifications@github.com>:

**Comment by smolleyes** [comment]
ok now when i try :

```
/home/sylvain/Documents/projets/git/StreamStudio/node_modules/upnpserver/api.js:52
      paths.forEach((path) => this.initPaths(path));
                           ^^
SyntaxError: Unexpected token =>
```

i use it in nwjs 0.12.3 (with --harmony)

**Comment by oeuillot** [comment]
For ES6, you must use nodejs > 4.0

I have specified that in the package.json :

  "engines": { "node": ">=4.2.0" },

Olivier

2016-01-27 10:04 GMT+01:00 smolleyes <notifications@github.com>:

**Comment by smolleyes** [comment]
ok so no way to use nwjs < 0.13 :/

**Comment by oeuillot** [comment]
You can't upgrade ?

Olivier

2016-01-27 10:20 GMT+01:00 smolleyes <notifications@github.com>:

**Comment by smolleyes** [comment]
nwjs 0.13 is a big shit for the moment and can t build my own version with custom codecs like 0.12.x :/ will wait :)

**Comment by oeuillot** [comment]
Which codec ?



2016-01-27 10:21 GMT+01:00 smolleyes <notifications@github.com>:

**Comment by smolleyes** [comment]
x265/opus/avi/flac .... :p

**Comment by oeuillot** [comment]
Rien que ça ! Effectivement !

Olivier

2016-01-27 10:29 GMT+01:00 smolleyes <notifications@github.com>:

**Comment by smolleyes** [comment]
bah oui lol j attend la version stable de nw13 pour m y reattaquer... ;)

**Comment by s-leger** [comment]
Hi guys,
The point with fs change detection is to correctly advertise clients of changes with events (update ids) for containers. With Icecast it's simple as there is only one, but for others i found it a little bit more complex.
Can't spend time for now on it, but i'll be happy to take a look at the new api.
Regards.

**Comment by s-leger** [comment]
For kerberos, there is two branch. 
Take a look at samba 4, as one is by far much simple to setup than another.

**Comment by rfigueroa** [comment]
@oeuillot master branch is broken since es6 merge

**Comment by oeuillot** [comment]
Hello rfigueroa, hope that last commits fix all problems !

**Comment by rfigueroa** [comment]
I'm still getting this error when running from master

`AssertionError: Invalid url parameter
    at ContentDirectoryService.getContentProvider (/.../upnpserver/lib/contentDirectoryService.js:1458:12)
    at AF_Metas.initialize (/.../upnpserver/lib/contentHandlers/af_metas.js:32:52)`

**Comment by oeuillot** [comment]
Hello @rfigueroa 
Can you set DEBUG=upnpserver:contentHandlers:AbstractMetas into your env variables
and post here the log
Thanks,

**Comment by rfigueroa** [comment]
It is working now, basePath in af_metas was the problem

**Comment by oeuillot** [comment]
Yes, I don't understand why if basePath is not defined, it crashes !

Best,

2016-02-17 22:22 GMT+01:00 rfigueroa <notifications@github.com>:

**Comment by rfigueroa** [comment]
can you provide some info into were basePath is supposed to point ? it is not on the configuration documentation and I don't have it as a env variable

`this.basePath = this._configuration.basePath || process.env.AF_METAS_PATH;`
